spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
   
      
  jpa:
      hibernate:
         format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: true
